### ISSUE TITLE
Can you upload the .cargo environment to do the expirement?

### ISSUE THREAD

**Issue by abietic** [jiegec/cs140e#4]
I'm trying to do this version cs140e but the rust toolchain can't build xargo of that version any more, mainly because of the dependencies. So can you upload a copy of your .cargo ? thanks

**Comment by jiegec** [comment]
The time cs140e was taken was around 2018 Feb so you cannot use the current toolchain.

**Comment by jiegec** [comment]
You can find a possibly compatible toolchain version at `rust-toolchain` file.

**Comment by abietic** [comment]
Unfortunately the rust-lang changes a lot over these years and nightly-2019-01-01 version can't do the compilation correctly.
So I have to find a way to download the older version xargo, which cargo couldn't help me with its --bins option (their dependencies!).
Luckily, the xargo github repos has provided the older version xargo binary I can download and put into .cargo directory to use.
I'm just getting started so I'm not sure if it will work for the whole exp, but it works fine for now, at least can build os/kernel without shooting hunderds of errors : )
Thank you
